/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/swagger.json": {
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/healthz": {
    get: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/auth-zero/create-account": {
    /** Create Ajanottaja account based on Auth0 register workflow action. */
    post: {
      parameters: {
        body: {
          body: {
            authZeroId: string;
            email: string;
          };
        };
      };
      responses: {
        200: {
          schema: {
            authZeroId: string;
            email: string;
            id: string;
            createdAt: string;
            updatedAt: string;
          };
        };
      };
    };
    /** Endpoints for Auth0 register and login workflows */
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/auth-zero/get-account/{auth-zero-id}": {
    /** Give auth0 acccess to ajanottaja id to use in custom claim in jwt during login workflow. */
    get: {
      parameters: {
        path: {
          authZeroId: string;
        };
      };
      responses: {
        200: {
          schema: {
            id: string;
          };
        };
      };
    };
    /** Endpoints for Auth0 register and login workflows */
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/intervals": {
    /** Returns list of intervals */
    get: {
      parameters: {
        query: {
          workDate: string;
        };
      };
      responses: {
        200: {
          schema: {
            id: string;
            createdAt: string;
            updatedAt: string;
            workdayId: string;
            interval: {
              beginning: string;
              end: string;
            };
          }[];
        };
      };
    };
    /** Endpoints for registeirng work days and intervals. */
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/intervals/active": {
    /** Return the active work interval if any exists. */
    get: {
      parameters: {};
      responses: {
        200: {
          schema: {
            id: string;
            createdAt: string;
            updatedAt: string;
            workdayId: string;
            interval: {
              beginning: string;
              end: string;
            };
          };
        };
        404: {
          schema: {
            status: 404;
            message: string;
          };
        };
      };
    };
    /** Endpoints for registeirng work days and intervals. */
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/intervals/start": {
    /** Upsert workday with workday duration and adds new work interval for the provided workday. */
    post: {
      parameters: {};
      responses: {
        200: {
          schema: {
            id: string;
            createdAt: string;
            updatedAt: string;
            workdayId: string;
            interval: {
              beginning: string;
              end: string;
            };
          };
        };
      };
    };
    /** Endpoints for registeirng work days and intervals. */
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
  "/intervals/stop": {
    /** Stop any active work interval, returns latest interval */
    post: {
      parameters: {};
      responses: {
        200: {
          schema: {
            id: string;
            createdAt: string;
            updatedAt: string;
            workdayId: string;
            interval: {
              beginning: string;
              end: string;
            };
          };
        };
      };
    };
    /** Endpoints for registeirng work days and intervals. */
    options: {
      parameters: {};
      responses: {
        default: unknown;
      };
    };
  };
}

export interface operations {}

export interface external {}
